import { type AddressList } from './interfaces/AddressList';
import { type BillingInfo } from './interfaces/BillingInfo';
import { type Channel } from './interfaces/Channel';
import { type FreshChatData } from './interfaces/FreshChatData';
import { type Platforms } from './interfaces/Platforms';
import { type Referral } from './interfaces/Referral';

export interface EddressUserParams {
  userUid: string;
  tenantUid: string;
  request: null | any;
  webhook: null | any;
  id: string;
  phoneNumber: string;
  telephoneNumber: null | any;
  email: string;
  name: string;
  profileImage: null | any;
  userName: null | any;
  password: null | any;
  createdOn: number;
  emailValidationSentDate: number;
  emailValidationDate: null | any;
  emailValidationKey: null | any;
  failedLoginAttemptsData: null | any;
  platforms: Platforms;
  userTags: null | any;
  channelTokens: Channel;
  channelProjectIds: Channel;
  isDeleted: boolean;
  deletedOn: null | any;
  gender: string;
  locale: string;
  legacyId: null;
  userVerificationData: null | any;
  passwordHistory: any[];
  addressList: AddressList[];
  currentOperationUid: string;
  referral: Referral;
  referrals: Record<string, Referral>;
  appIdentifier: string;
  authProvider: string;
  authUid: string;
  favoriteProducts: null | any;
  notifyProducts: string[];
  addressesSynced: boolean;
  billingInfo: BillingInfo;
  amountInWallet: number;
  gatewayCustomerId: null | any;
  gatewayCustomerIds: null | any;
  favoriteStores: null | any;
  lastPaymentSessionData: null | any;
  businessInfo: null | any;
  isPhoneVerified: boolean;
  freshChatData: FreshChatData;
  channel: string;
  uidTenant: string;
  uidUser: string;
  yeloUser: boolean;
  pushToken: string;
  pushProjectId: string;
  firstName: string;
  fullName: string;
  userPhoneNumber: string;
  userEmail: string;
}
